
<?php
// module/Album/view/album/album/add.phtml:

$title = 'Register account';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('register', array('action' => 'register')));

$form->prepare();

echo $this->form()->openTag($form);
echo $this->formSubmit($form->get('register'));
?>

<?php
echo $this->form()->closeTag();
?>
</html>